extensions:
  client:
    endpoints:
      - wss://op-demo.alt.technology/ws
  eth_api:
    stale_timeout_seconds: 180 # rotate endpoint if no new blocks for 3 minutes
  telemetry:
    provider: none
  prometheus:
    port: 9616
    listen_address: "0.0.0.0"
    prefix: "subway"
  cache:
    default_ttl_seconds: 60
    default_size: 500
  server:
    port: 8545
    listen_address: '0.0.0.0'
    max_connections: 2000
    max_batch_size: 10
    cors: all
  whitelist:
    eth_call_whitelist:
      # allow 0x01 to call 0x02
      - from: 0000000000000000000000000000000000000001
        to: 0000000000000000000000000000000000000002
      # allow anyone to call 0x01
      - to: 0000000000000000000000000000000000000000
      # allow 0x02 to create contract
      - from: 0000000000000000000000000000000000000002
        to: create
    tx_whitelist:
      # allow 0x01 to call or create in tx.
      - from: 0000000000000000000000000000000000000001
middlewares:
  methods:
    - whitelist
    - response
    - block_tag
    - cache
    - upstream
  subscriptions:
    - upstream

rpcs: rpc_configs/geth.yml
